var appConstants = {
  HTTPSTATUS: "HTTPSTATUS",
  SAVE_CLICKED: "SAVE_CLICKED",
  FIRSTNAME: "FIRSTNAME",
  LASTNAME: "LASTNAME",
  SUBJECTS: "SUBJECTS",
  ABSTRACT: "ABSTRACT",
  ARTICLE: "ARTICLE",
  INTRADAYTICKET: "INTRADAYTICKET",
  MARKET: "MARKET",
  STARTDATE: "STARTDATE",
  ENDDATE: "ENDDATE",
  COMPANY_CODE: "COMPANY_CODE",
  SEND_REQUEST: "SEND_REQUEST",
  AUTOCORRELATION_INTRADAY: "AUTOCORRELATION_INTRADAY"
};
module.exports = appConstants;